"""phone_number_and_time_validators

Revision ID: 848fd1f48f03
Revises: 925d7e737439
Create Date: 2025-03-09 15:24:57.534735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848fd1f48f03'
down_revision: Union[str, None] = '925d7e737439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'phone_number')
    # ### end Alembic commands ###
